version: '3'

services:
  userdb:
    image: mysql:8.0
    container_name: user_db
    volumes:
        - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: advancedroot
      MYSQL_DATABASE: userdb
      MYSQL_USER: service_user
      MYSQL_PASSWORD: service_user
    ports:
      - "9906:3306"
    expose:
      - "9906"  
  web:
    build: .
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - userdb
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8000:80"
    stdin_open: true
    tty: true

  recipedb:
    image: mysql:8.0
    container_name: recipe_db
    volumes:
        - recipedata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: reciperoot
      MYSQL_DATABASE: recipedb
      MYSQL_USER: recipe_user
      MYSQL_PASSWORD: recipe_user
    ports:
      - "9907:3306"
    expose:
      - "9907"  

volumes:
  dbdata:
  recipedata: