version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: advancedroot
      MYSQL_DATABASE: userdb
      MYSQL_USER: service_user
      MYSQL_PASSWORD: service_user
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8000:80"
    stdin_open: true
    tty: true
